defaults: &defaults
  event:
    name: "RailsCamp 2013"
    start_time: 2013-07-26 20:00:00
    end_time: 2013-07-28 17:00:00
  host: "sessions.railscamp.de"
  mailers:
    from: "mail@railscamp.de"
  errors:
    from: "mail@railscamp.de"
    to:
      - "felix@plan.io"
      - "jakob@railslove.com"
      - "sebastian@kip.pe"

development:
  <<: *defaults
  host: "activities.dev:3000"

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
